# Enter your program into this window
name=input("Enter a name:")
adjective1=input("Enter an adjective:")
adjective2=input ("Enter an adjective:")
adverb=input("Enter an adverb:")
food1=input("Enter a food:")
food2=input ("Enter another food:")
noun=input("Ender a noun:")
place=input("Enter a place:")
verb=input("Enter a verb:")
print()
print( str( name +" was planning a dream vacation to " + place + ".") )
print (str(name + " was especially looking forward to trying the local") )
print(str("cuisine, including " + adjective1 +" "+ food1 + " and " + food2 + ".") )
print("")
print(str( name + " will have to practice the language " + adverb + " to") )
print(str("make it easier to " + verb + " with people.") )
print ("")
print(str(name + " has a long list of sights to see, including the") )
print(str( noun + " museum and the " + adjective2 + " park.") )
